config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  get '/signup', to: "users#new"
  post '/users', to: "users#create"

  resources :users, only: [:create]
  resources :lists, only: [:create, :destroy, :edit, :update]
  
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user

  validates :title, :description, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :lists

  validates :name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :hiok
  protect_from_forgery with: :exception

  def hiok
    "HiOK"
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def create
    List.create(list_params)
    redirect_to '/' 
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    List.find(params[:id]).update_attributes(list_params)
    redirect_to '/' 
  end

  def destroy
    List.delete(params["id"])
    redirect_to :back
  end

  private
    def list_params
      params.require(:list).permit(:title, :description, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_user_home.html.erb
<% @user = current_user %>
<% @list = List.new %>
<h3>
<%= @user.name %>
<%= @user.email %>
</h3>

<%= form_for @list do |f| %>
  Title: <%= f.text_field :title %>
  Description: <%= f.text_field :description %>
  <%= f.hidden_field :user_id, :value => @user.id %>
  <%= f.submit "Submit" %>
<% end %>

<ul>
<% @user.lists.each do |list| %>
  <li>
    <h3><%=list.title %></h3>
    <h5><%=list.description%></h5>
    <%=link_to "Edit", edit_list_path(list.id) %>
    <%=link_to "Delete", list_path(list.id), method: :delete %>
  </li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/edit.html.erb
<%= form_for @list do |f| %>
  Title: <%= f.text_field :title %>
  Description: <%= f.text_field :description %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>


<% end %>

app/views/welcome/index.html.erb
<h1>This is the welcome page</h1>

<% if current_user %>
  <p> <%= "Hello #{current_user.name}"%> </p>
  <%=link_to "Logout", logout_path %>
  <%= render "layouts/user_home" %>


<% else %>
  <%=link_to "Login", login_path %>
  <%=link_to "Sign Up", signup_path %>
<% end %>